### ISSUE TITLE
Only one CANFD message is being sent

### ISSUE THREAD

**Issue by lalitheranti** [pierremolinaro/acan2517FD#13]
I am currently able to send only one can fd message and when I send multiple messages in one loop, only the top message is being sent. other messages are sent only for just few sec and it stopped. only the top message is continously being sent. why is it so? is there any change that I should do for setting the lib? in case of CAN , i can send multiple messages at sametime using ACAN2517 lib.

**Comment by MattLeright** [comment]
Hi there,

I am having the same problem.  Were you able to come to a solution?

Thanks,
Matt
