### ISSUE TITLE
Cannot work with CAN FD 500kbps and 5Mbps

### ISSUE THREAD

**Issue by pedrodpj** [pierremolinaro/acan2517FD#22]
Hi,

I'm using CANFD with 500kpbs and 5Mbps, but your code only implements max DataBitRateFactor::x8.

To solve my problem I've changed your enum:

enum class DataBitRateFactor : uint8_t {
    x1 = 1,
    x2 = 2,
    x3 = 3,
    x4 = 4,
    x5 = 5,
    x6 = 6,
    x7 = 7,
    x8 = 8,
    x9 = 9,    //add for x9
    x10 = 10 //add for x10
} ;

Could you update your library?

Thanks and best regards

**Comment by pierremolinaro** [comment]
Hello,

Thank you for your message, I will add soon the x9 and x10 data bit rate factors and make a new release.

Best regards,

Pierre Molinaro

**Comment by Flole998** [comment]
This has been fixed and can be closed :)

**Comment by pedrodpj** [comment]
Bug fixed
