### ISSUE TITLE
Conventional/Normal CAN messages possible?

### ISSUE THREAD

**Issue by bwiessneth** [pierremolinaro/acan2517FD#30]
Looking at the source I found that both CAN-FD and normal CAN messages are defined in the corresponding files (CANFDMessage.h,  CANMessage.h), however the implementations for `receive` or `tryToSend` are using the CANFDMessage definitions.

This leads me to the question: Does your library support conventional / non-FD CAN messages?

According to the MCP2518 datasheet  (page 27) the OPMOD will default to `000` which results in "Set Normal CAN FD mode; supports mixing of CAN FD and Classic CAN 2.0 frames". At this point I only skimmed over the source, but maybe somebody who knows this library better already tested this or knows a definite answer to this.

**Comment by pierremolinaro** [comment]
Yes, my library support CAN 2.0B messages.

For sending a CAN 2.0B message, call tryToSend, either with a CANMessage argument, either with a CANFDMessage argument. The CANFDMessage class has a constructor for initializing from a CANMessage.

The receive method is able to get any message, either a CANFD one, etither a CAN 2.0B one. Just test the type property: its value is CAN_DATA for a CAN 2.0B data frame,  CAN_REMOTE for a CAN 2.0B remote frame (and CANFD_NO_BIT_RATE_SWITCH or CANFD_WITH_BIT_RATE_SWITCH for a CANFD frame).

Pierre

**Comment by bwiessneth** [comment]
Hi @pierremolinaro, thanks for your clarification! 👍
