### ISSUE TITLE
Can't loopback new library with an arduino mega

### ISSUE THREAD

**Issue by E-nodev** [pierremolinaro/acan2517FD#7]
Hello, 
I tried the sample test LoopBackDemoArduinoUno, before the new release it's ok,
But now i've a Configuration error 0x1 and i can't received anything.
Send return no error.
Can you help me ?

Thank you

**Comment by pierremolinaro** [comment]
Hello,

Error 0x1 (kRequestedConfigurationModeTimeOut) means that MCP2517FD cannot enter in configuration mode in 2 ms.

I have noticed that this error sometimes comes after a new sketch is uploaded. I have solved by power off and then power the Arduino board and the MCP2517FD.

I just had the loopbackdemo sketch executed on my teensy, it works without any problems.

Does this error occur always ?

Pierre

**Comment by E-nodev** [comment]
Hello, 
The error occur always after 5 try to unplug the board and plug. 
It's ok with your previours library, but with the new i have the same error code.
 
Thank you for your help and your reactivity.

Fred

**Comment by tizianotosco** [comment]
Hello,
I tried the LoopBackDemoArduinoUno sample test with ArduinoMega but it doesn't work. Are there any particular configs to modify?
Can you help me?
Thank you

**Comment by E-nodev** [comment]
It works with a old version :
https://www.arduinolibraries.info/libraries/acan2517-fd
I don't remember which version sorry :/

Good luck

**Comment by mpfarr** [comment]
Hi,
i just started playing with acan2517-fd on Teensy 3.6.

I face an undocumented error:

Using pin #0 for MOSI: yes
Using pin #1 for MISO: yes
Using pin #32 for SCK: yes
Configure ACAN2517FD
MCP2517FD RAM Usage: 2016 bytes
OSC 61
Configuration error 0x20000
Send failure
Send failure

**Comment by pierremolinaro** [comment]
Hello,

The 0x20000 error is documented (see table 7 page 39), it is kX10PLLNotReadyWithin1MS. What is the frequency  of the quartz that drives the MCP2517FD ? For using ACAN2517FDSettings::OSC_4MHz10xPLL as parameter of the begin method, you should have a 4 MHz quartz.

Regards,

Pierre Molinaro

**Comment by mpfarr** [comment]
Hi,
i tried the LoopBackDemoArduinoUno on Adruino Uno with MCP2518FD click. I always get configuration  error 0x1. I already double checked MOSI/MOSI/SCK/SS.

Any suggestion with Arduino uno?

br,
Matthias

**Comment by mpfarr** [comment]
problem solved: logic level of MCP2518FD click board was wrong.

sorry
